from __future__ import annotations

from collections.abc import Callable
from datetime import time as dt_time
import logging
import re

from homeassistant.components.time import TimeEntity
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.entity import DeviceInfo, EntityCategory
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .battery_schedule_editor import (
    BatteryScheduleEditorEntity,
    battery_scheduler_enabled,
)
from .const import DOMAIN
from .coordinator import EnphaseCoordinator
from .entity import battery_schedule_extra_state_attributes
from .entity_cleanup import prune_managed_entities
from .evse_schedule_editor import (
    EvseScheduleEditorEntity,
    evse_schedule_editor_active,
)
from .log_redaction import redact_identifier
from .runtime_helpers import (
    inventory_type_available as _type_available,
    inventory_type_device_info as _type_device_info,
)
from .runtime_data import EnphaseConfigEntry, get_runtime_data

PARALLEL_UPDATES = 0
_LOGGER = logging.getLogger(__name__)
_AUTO_SUFFIX_RE = re.compile(r"^\d+$")


def _time_entity_id_migrations(coord: EnphaseCoordinator) -> dict[str, tuple[str, str]]:
    return {
        f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_start_time": (
            "time.charge_from_grid_start_time",
            "time.charge_from_grid_schedule_from_time",
        ),
        f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_end_time": (
            "time.charge_from_grid_end_time",
            "time.charge_from_grid_schedule_to_time",
        ),
    }


def _migrated_time_entity_id(
    current_entity_id: str, legacy_entity_id: str, target_entity_id: str
) -> str | None:
    """Return canonical target entity_id, preserving numeric collision suffixes."""
    if current_entity_id == target_entity_id:
        return None

    # Keep already-migrated canonical auto-suffixed IDs unchanged.
    target_prefix = f"{target_entity_id}_"
    if current_entity_id.startswith(target_prefix):
        target_suffix = current_entity_id[len(target_prefix) :]
        if _AUTO_SUFFIX_RE.fullmatch(target_suffix):
            return None

    # Preserve legacy auto-suffixes generated by HA object-id collisions.
    legacy_prefix = f"{legacy_entity_id}_"
    if current_entity_id.startswith(legacy_prefix):
        suffix = current_entity_id[len(legacy_prefix) :]
        if _AUTO_SUFFIX_RE.fullmatch(suffix):
            return f"{target_entity_id}_{suffix}"

    # Strong migration mode: preserve any trailing numeric suffix and
    # otherwise force canonical target IDs (including former custom IDs).
    base, _, suffix = current_entity_id.rpartition("_")
    if base and _AUTO_SUFFIX_RE.fullmatch(suffix):
        return f"{target_entity_id}_{suffix}"
    return target_entity_id


def _site_has_battery(coord: EnphaseCoordinator) -> bool:
    has_encharge = getattr(coord, "battery_has_encharge", None)
    return has_encharge is not False


def _cfg_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "charge_from_grid_schedule_available", False):
        return True
    if not getattr(coord, "charge_from_grid_control_available", False):
        return False
    if not getattr(coord, "charge_from_grid_schedule_supported", False):
        return False
    start_time = getattr(coord, "battery_charge_from_grid_start_time", None)
    end_time = getattr(coord, "battery_charge_from_grid_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_charge_begin_time", None)
    end = getattr(coord, "_battery_charge_end_time", None)
    return begin is not None and end is not None


def _dtg_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "discharge_to_grid_schedule_available", False):
        return True
    if not getattr(coord, "discharge_to_grid_schedule_supported", False):
        return False
    start_time = getattr(coord, "battery_discharge_to_grid_start_time", None)
    end_time = getattr(coord, "battery_discharge_to_grid_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_dtg_begin_time", None)
    end = getattr(coord, "_battery_dtg_end_time", None)
    if begin is None:
        begin = getattr(coord, "_battery_dtg_control_begin_time", None)
    if end is None:
        end = getattr(coord, "_battery_dtg_control_end_time", None)
    return begin is not None and end is not None


def _rbd_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "restrict_battery_discharge_schedule_available", False):
        return True
    if not getattr(coord, "restrict_battery_discharge_schedule_supported", False):
        return False
    start_time = getattr(coord, "battery_restrict_battery_discharge_start_time", None)
    end_time = getattr(coord, "battery_restrict_battery_discharge_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_rbd_begin_time", None)
    end = getattr(coord, "_battery_rbd_end_time", None)
    if begin is None:
        begin = getattr(coord, "_battery_rbd_control_begin_time", None)
    if end is None:
        end = getattr(coord, "_battery_rbd_control_end_time", None)
    return True


def _default_schedule_time_for_create(
    schedule_type: str, *, end: bool = False
) -> dt_time | None:
    normalized = str(schedule_type).lower()
    if normalized == "rbd":
        return dt_time(16, 0) if end else dt_time(1, 0)
    return None


def _battery_schedule_editor_active(
    coord: EnphaseCoordinator, entry: EnphaseConfigEntry | None
) -> bool:
    client = getattr(coord, "client", None)
    return bool(
        battery_scheduler_enabled(entry)
        and callable(getattr(client, "battery_schedules", None))
        and all(
            callable(getattr(client, method, None))
            for method in (
                "create_battery_schedule",
                "update_battery_schedule",
                "delete_battery_schedule",
            )
        )
    )


def _retained_site_time_unique_ids(
    coord: EnphaseCoordinator, entry: EnphaseConfigEntry | None = None
) -> set[str]:
    unique_ids: set[str] = set()
    if not _type_available(coord, "encharge"):
        return unique_ids
    editor_active = _battery_schedule_editor_active(coord, entry)
    cfg_supported = getattr(coord, "charge_from_grid_schedule_supported", None)
    dtg_supported = getattr(coord, "discharge_to_grid_schedule_supported", None)
    rbd_supported = getattr(
        coord, "restrict_battery_discharge_schedule_supported", None
    )
    if not editor_active and (
        _cfg_schedule_edit_available(coord) or cfg_supported is not False
    ):
        unique_ids.update(
            {
                f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_start_time",
                f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_end_time",
            }
        )
    if not editor_active:
        if _dtg_schedule_edit_available(coord) or dtg_supported is not False:
            unique_ids.update(
                {
                    f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_start_time",
                    f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_end_time",
                }
            )
        if _rbd_schedule_edit_available(coord) or rbd_supported is not False:
            unique_ids.update(
                {
                    f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_start_time",
                    f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_end_time",
                }
            )
    if editor_active:
        unique_ids.update(
            {
                f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_start_time",
                f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_end_time",
            }
        )
    return unique_ids


async def async_setup_entry(
    hass: HomeAssistant,
    entry: EnphaseConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    coord: EnphaseCoordinator = get_runtime_data(entry).coordinator
    added_site_time_unique_ids: set[str] = set()
    known_serials: set[str] = set()
    active_site_time_unique_ids: set[str] = set()

    ent_reg = er.async_get(hass)
    rename_by_unique = _time_entity_id_migrations(coord)
    for registry_entry in er.async_entries_for_config_entry(ent_reg, entry.entry_id):
        migration = rename_by_unique.get(registry_entry.unique_id)
        if migration is None:
            continue
        legacy_entity_id, target_entity_id = migration
        migrated_entity_id = _migrated_time_entity_id(
            registry_entry.entity_id, legacy_entity_id, target_entity_id
        )
        if migrated_entity_id is None:
            continue
        try:
            ent_reg.async_update_entity(
                registry_entry.entity_id,
                new_entity_id=migrated_entity_id,
            )
        except ValueError:
            _LOGGER.debug(
                "Could not rename schedule time entity during migration (%s -> %s)",
                redact_identifier(registry_entry.entity_id),
                redact_identifier(migrated_entity_id),
            )

    def _managed_site_time_unique_ids() -> set[str]:
        return {
            f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_start_time",
            f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_end_time",
            f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_start_time",
            f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_end_time",
            f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_start_time",
            f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_end_time",
            f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_start_time",
            f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_end_time",
            f"{DOMAIN}_site_{coord.site_id}_battery_new_schedule_start_time",
            f"{DOMAIN}_site_{coord.site_id}_battery_new_schedule_end_time",
        }

    def _charger_schedule_time_unique_ids(sn: str) -> set[str]:
        return {
            f"{DOMAIN}_{sn}_schedule_edit_start_time",
            f"{DOMAIN}_{sn}_schedule_edit_end_time",
        }

    def _site_time_entities_by_unique_id(
        retained_site_time_unique_ids: set[str],
    ) -> dict[str, TimeEntity]:
        entity_factories: dict[str, Callable[[], TimeEntity]] = {
            f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_start_time": lambda: ChargeFromGridStartTimeEntity(
                coord
            ),
            f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_end_time": lambda: ChargeFromGridEndTimeEntity(
                coord
            ),
            f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_start_time": lambda: DischargeToGridStartTimeEntity(
                coord
            ),
            f"{DOMAIN}_site_{coord.site_id}_discharge_to_grid_end_time": lambda: DischargeToGridEndTimeEntity(
                coord
            ),
            f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_start_time": lambda: RestrictBatteryDischargeStartTimeEntity(
                coord
            ),
            f"{DOMAIN}_site_{coord.site_id}_restrict_battery_discharge_end_time": lambda: RestrictBatteryDischargeEndTimeEntity(
                coord
            ),
        }
        if battery_scheduler_enabled(entry):
            entity_factories[
                f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_start_time"
            ] = lambda: BatteryScheduleEditStartTimeEntity(coord, entry)
            entity_factories[
                f"{DOMAIN}_site_{coord.site_id}_battery_schedule_edit_end_time"
            ] = lambda: BatteryScheduleEditEndTimeEntity(coord, entry)

        active_site_time_unique_ids = retained_site_time_unique_ids

        return {
            unique_id: factory()
            for unique_id, factory in entity_factories.items()
            if unique_id in active_site_time_unique_ids
        }

    @callback
    def _async_sync_site_entities() -> None:
        nonlocal active_site_time_unique_ids
        inventory_ready = bool(getattr(coord, "_devices_inventory_ready", False))
        retained_site_time_unique_ids = _retained_site_time_unique_ids(coord, entry)
        active_site_time_unique_ids = set()
        if _site_has_battery(coord) and _type_available(coord, "encharge"):
            active_site_time_unique_ids = retained_site_time_unique_ids
            current_site_entities = _site_time_entities_by_unique_id(
                retained_site_time_unique_ids
            )
            site_entities = [
                entity
                for unique_id, entity in current_site_entities.items()
                if unique_id not in added_site_time_unique_ids
            ]
            if site_entities:
                async_add_entities(site_entities, update_before_add=False)
                added_site_time_unique_ids.update(
                    entity.unique_id
                    for entity in site_entities
                    if isinstance(entity.unique_id, str)
                )
        added_site_time_unique_ids.intersection_update(active_site_time_unique_ids)
        if not inventory_ready:
            return
        prune_managed_entities(
            ent_reg,
            entry.entry_id,
            domain="time",
            active_unique_ids=active_site_time_unique_ids,
            is_managed=lambda unique_id: unique_id in _managed_site_time_unique_ids(),
        )

    @callback
    def _async_sync_charger_entities() -> None:
        inventory_ready = bool(getattr(coord, "_devices_inventory_ready", False))
        current_serials = {sn for sn in coord.iter_serials() if sn}
        serials = [sn for sn in current_serials if sn not in known_serials]
        entities: list[TimeEntity] = []
        if evse_schedule_editor_active(coord, entry):
            for sn in serials:
                entities.append(EvseScheduleEditStartTimeEntity(coord, entry, sn))
                entities.append(EvseScheduleEditEndTimeEntity(coord, entry, sn))
        if entities:
            async_add_entities(entities, update_before_add=False)
        known_serials.intersection_update(current_serials)
        known_serials.update(serials)
        if not inventory_ready:
            return
        active_unique_ids: set[str] = set()
        if evse_schedule_editor_active(coord, entry):
            for sn in current_serials:
                active_unique_ids.update(_charger_schedule_time_unique_ids(sn))
        prune_managed_entities(
            ent_reg,
            entry.entry_id,
            domain="time",
            active_unique_ids=active_unique_ids | active_site_time_unique_ids,
            is_managed=lambda unique_id: (
                unique_id in _managed_site_time_unique_ids()
                or unique_id.endswith(
                    ("_schedule_edit_start_time", "_schedule_edit_end_time")
                )
            ),
        )

    add_topology_listener = getattr(coord, "async_add_topology_listener", None)
    if callable(add_topology_listener):
        entry.async_on_unload(add_topology_listener(_async_sync_site_entities))
        entry.async_on_unload(add_topology_listener(_async_sync_charger_entities))
    add_listener = getattr(coord, "async_add_listener", None)
    if callable(add_listener):
        entry.async_on_unload(add_listener(_async_sync_site_entities))
        entry.async_on_unload(add_listener(_async_sync_charger_entities))
    _async_sync_site_entities()
    _async_sync_charger_entities()


class _BaseChargeFromGridTimeEntity(CoordinatorEntity, TimeEntity):
    _attr_has_entity_name = True

    def __init__(self, coord: EnphaseCoordinator, suffix: str) -> None:
        super().__init__(coord)
        self._coord = coord
        self._attr_unique_id = f"{DOMAIN}_site_{coord.site_id}_{suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        if not super().available:
            return False
        return _type_available(
            self._coord, "encharge"
        ) and _cfg_schedule_edit_available(self._coord)

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {
            "start_time": self._coord.battery_charge_from_grid_start_time,
            "end_time": self._coord.battery_charge_from_grid_end_time,
            "schedule_status": self._coord.battery_cfg_schedule_status,
            "schedule_pending": self._coord.battery_cfg_schedule_pending,
            "schedule_enabled": self._coord.battery_charge_from_grid_schedule_enabled,
        }

    @property
    def extra_state_attributes(self) -> dict[str, object]:
        return battery_schedule_extra_state_attributes(
            self._coord, **self._extra_schedule_state_attributes()
        )

    @property
    def device_info(self) -> DeviceInfo:
        info = _type_device_info(self._coord, "encharge")
        if info is not None:
            return info
        return DeviceInfo(
            identifiers={(DOMAIN, f"type:{self._coord.site_id}:encharge")},
            manufacturer="Enphase",
        )


class ChargeFromGridStartTimeEntity(_BaseChargeFromGridTimeEntity):
    _attr_translation_key = "charge_from_grid_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(coord, "charge_from_grid_start_time")

    @property
    def suggested_object_id(self) -> str | None:
        return "charge_from_grid_schedule_from_time"

    @property
    def native_value(self) -> dt_time | None:
        return self._coord.battery_charge_from_grid_start_time

    async def async_set_value(self, value: dt_time) -> None:
        if (
            self._coord.charge_from_grid_schedule_available
            and self._coord.battery_charge_from_grid_enabled is True
        ):
            await self._coord.async_set_charge_from_grid_schedule_time(start=value)
            return
        await self._coord.async_update_cfg_schedule(start=value)


class ChargeFromGridEndTimeEntity(_BaseChargeFromGridTimeEntity):
    _attr_translation_key = "charge_from_grid_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(coord, "charge_from_grid_end_time")

    @property
    def suggested_object_id(self) -> str | None:
        return "charge_from_grid_schedule_to_time"

    @property
    def native_value(self) -> dt_time | None:
        return self._coord.battery_charge_from_grid_end_time

    async def async_set_value(self, value: dt_time) -> None:
        if (
            self._coord.charge_from_grid_schedule_available
            and self._coord.battery_charge_from_grid_enabled is True
        ):
            await self._coord.async_set_charge_from_grid_schedule_time(end=value)
            return
        await self._coord.async_update_cfg_schedule(end=value)


class _BaseNamedBatteryScheduleTimeEntity(CoordinatorEntity, TimeEntity):
    _attr_has_entity_name = True

    def __init__(
        self,
        coord: EnphaseCoordinator,
        *,
        suffix: str,
        schedule_type: str,
        availability_check,
        value_attr: str,
        setter_name: str,
        suggested_object_id: str,
    ) -> None:
        super().__init__(coord)
        self._coord = coord
        self._schedule_type = schedule_type
        self._availability_check = availability_check
        self._value_attr = value_attr
        self._setter_name = setter_name
        self._suggested_object_id = suggested_object_id
        self._attr_unique_id = f"{DOMAIN}_site_{coord.site_id}_{suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        if not super().available:
            return False
        return _type_available(self._coord, "encharge") and self._availability_check(
            self._coord
        )

    @property
    def suggested_object_id(self) -> str | None:
        return self._suggested_object_id

    @property
    def native_value(self) -> dt_time | None:
        value = getattr(self._coord, self._value_attr)
        if value is not None:
            return value
        default_value = _default_schedule_time_for_create(
            self._schedule_type,
            end=self._schedule_endpoint_key() == "end",
        )
        if default_value is not None and self._availability_check(self._coord):
            return default_value
        return None

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {}

    @property
    def extra_state_attributes(self) -> dict[str, object]:
        return battery_schedule_extra_state_attributes(
            self._coord, **self._extra_schedule_state_attributes()
        )

    @property
    def device_info(self) -> DeviceInfo:
        info = _type_device_info(self._coord, "encharge")
        if info is not None:
            return info
        return DeviceInfo(
            identifiers={(DOMAIN, f"type:{self._coord.site_id}:encharge")},
            manufacturer="Enphase",
        )

    async def async_set_value(self, value: dt_time) -> None:
        await getattr(self._coord, self._setter_name)(
            **{self._schedule_endpoint_key(): value}
        )

    def _schedule_endpoint_key(self) -> str:
        return "start"


class _BaseNamedBatteryScheduleStartTimeEntity(_BaseNamedBatteryScheduleTimeEntity):
    def _schedule_endpoint_key(self) -> str:
        return "start"


class _BaseNamedBatteryScheduleEndTimeEntity(_BaseNamedBatteryScheduleTimeEntity):
    def _schedule_endpoint_key(self) -> str:
        return "end"


class DischargeToGridStartTimeEntity(_BaseNamedBatteryScheduleStartTimeEntity):
    _attr_translation_key = "discharge_to_grid_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="discharge_to_grid_start_time",
            schedule_type="dtg",
            availability_check=_dtg_schedule_edit_available,
            value_attr="battery_discharge_to_grid_start_time",
            setter_name="async_set_discharge_to_grid_schedule_time",
            suggested_object_id="discharge_to_grid_schedule_from_time",
        )

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {
            "start_time": self._coord.battery_discharge_to_grid_start_time,
            "end_time": self._coord.battery_discharge_to_grid_end_time,
            "schedule_status": self._coord.battery_dtg_schedule_status,
            "schedule_pending": self._coord.battery_dtg_schedule_pending,
            "schedule_enabled": self._coord.battery_discharge_to_grid_schedule_enabled,
        }


class DischargeToGridEndTimeEntity(_BaseNamedBatteryScheduleEndTimeEntity):
    _attr_translation_key = "discharge_to_grid_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="discharge_to_grid_end_time",
            schedule_type="dtg",
            availability_check=_dtg_schedule_edit_available,
            value_attr="battery_discharge_to_grid_end_time",
            setter_name="async_set_discharge_to_grid_schedule_time",
            suggested_object_id="discharge_to_grid_schedule_to_time",
        )

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {
            "start_time": self._coord.battery_discharge_to_grid_start_time,
            "end_time": self._coord.battery_discharge_to_grid_end_time,
            "schedule_status": self._coord.battery_dtg_schedule_status,
            "schedule_pending": self._coord.battery_dtg_schedule_pending,
            "schedule_enabled": self._coord.battery_discharge_to_grid_schedule_enabled,
        }


class RestrictBatteryDischargeStartTimeEntity(_BaseNamedBatteryScheduleStartTimeEntity):
    _attr_translation_key = "restrict_battery_discharge_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="restrict_battery_discharge_start_time",
            schedule_type="rbd",
            availability_check=_rbd_schedule_edit_available,
            value_attr="battery_restrict_battery_discharge_start_time",
            setter_name="async_set_restrict_battery_discharge_schedule_time",
            suggested_object_id="restrict_battery_discharge_schedule_from_time",
        )

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {
            "start_time": self._coord.battery_restrict_battery_discharge_start_time,
            "end_time": self._coord.battery_restrict_battery_discharge_end_time,
            "schedule_status": self._coord.battery_rbd_schedule_status,
            "schedule_pending": self._coord.battery_rbd_schedule_pending,
            "schedule_enabled": self._coord.battery_restrict_battery_discharge_schedule_enabled,
        }


class RestrictBatteryDischargeEndTimeEntity(_BaseNamedBatteryScheduleEndTimeEntity):
    _attr_translation_key = "restrict_battery_discharge_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="restrict_battery_discharge_end_time",
            schedule_type="rbd",
            availability_check=_rbd_schedule_edit_available,
            value_attr="battery_restrict_battery_discharge_end_time",
            setter_name="async_set_restrict_battery_discharge_schedule_time",
            suggested_object_id="restrict_battery_discharge_schedule_to_time",
        )

    def _extra_schedule_state_attributes(self) -> dict[str, object]:
        return {
            "start_time": self._coord.battery_restrict_battery_discharge_start_time,
            "end_time": self._coord.battery_restrict_battery_discharge_end_time,
            "schedule_status": self._coord.battery_rbd_schedule_status,
            "schedule_pending": self._coord.battery_rbd_schedule_pending,
            "schedule_enabled": self._coord.battery_restrict_battery_discharge_schedule_enabled,
        }


def _parse_editor_time(value: str | None) -> dt_time | None:
    if not value:
        return None
    try:
        return dt_time.fromisoformat(value)
    except ValueError:
        return None


class _BatteryScheduleEditorTimeEntity(BatteryScheduleEditorEntity, TimeEntity):
    _attr_has_entity_name = True
    _attr_entity_category = EntityCategory.CONFIG

    def __init__(
        self,
        coord: EnphaseCoordinator,
        entry: EnphaseConfigEntry,
        *,
        unique_suffix: str,
        translation_key: str,
        key: str,
    ) -> None:
        super().__init__(coord, entry)
        self._attr_translation_key = translation_key
        self._key = key
        self._attr_unique_id = f"{DOMAIN}_site_{coord.site_id}_{unique_suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        client = getattr(self._coord, "client", None)
        return (
            super().available
            and battery_scheduler_enabled(self._entry)
            and _type_available(self._coord, "encharge")
            and getattr(self._coord, "battery_write_access_confirmed", False)
            and callable(getattr(client, "battery_schedules", None))
            and callable(getattr(client, "create_battery_schedule", None))
            and callable(getattr(client, "update_battery_schedule", None))
            and callable(getattr(client, "delete_battery_schedule", None))
            and self._editor is not None
        )

    @property
    def native_value(self) -> dt_time | None:
        if self._editor is None:
            return None
        return _parse_editor_time(getattr(self._editor.edit, self._key))

    @property
    def device_info(self) -> DeviceInfo:
        info = _type_device_info(self._coord, "encharge")
        if info is not None:
            return info
        return DeviceInfo(
            identifiers={(DOMAIN, f"type:{self._coord.site_id}:encharge")},
            manufacturer="Enphase",
        )


class BatteryScheduleEditStartTimeEntity(_BatteryScheduleEditorTimeEntity):
    def __init__(self, coord: EnphaseCoordinator, entry: EnphaseConfigEntry) -> None:
        super().__init__(
            coord,
            entry,
            unique_suffix="battery_schedule_edit_start_time",
            translation_key="battery_schedule_edit_start_time",
            key="start_time",
        )

    async def async_set_value(self, value: dt_time) -> None:
        if self._editor is not None:
            self._editor.set_edit_time("start_time", value)


class BatteryScheduleEditEndTimeEntity(_BatteryScheduleEditorTimeEntity):
    def __init__(self, coord: EnphaseCoordinator, entry: EnphaseConfigEntry) -> None:
        super().__init__(
            coord,
            entry,
            unique_suffix="battery_schedule_edit_end_time",
            translation_key="battery_schedule_edit_end_time",
            key="end_time",
        )

    async def async_set_value(self, value: dt_time) -> None:
        if self._editor is not None:
            self._editor.set_edit_time("end_time", value)


class _EvseScheduleEditorTimeEntity(EvseScheduleEditorEntity, TimeEntity):
    _attr_has_entity_name = True
    _attr_entity_category = EntityCategory.CONFIG

    def __init__(
        self,
        coord: EnphaseCoordinator,
        entry: EnphaseConfigEntry,
        sn: str,
        *,
        unique_suffix: str,
        translation_key: str,
        key: str,
    ) -> None:
        super().__init__(coord, entry, sn)
        self._attr_translation_key = translation_key
        self._key = key
        self._attr_unique_id = f"{DOMAIN}_{sn}_{unique_suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        return (
            super().available
            and evse_schedule_editor_active(self._coord, self._entry)
            and self._editor is not None
        )

    @property
    def native_value(self) -> dt_time | None:
        if self._editor is None:
            return None
        value = getattr(self._editor.form_state(self._sn), self._key)
        return _parse_editor_time(value)


class EvseScheduleEditStartTimeEntity(_EvseScheduleEditorTimeEntity):
    def __init__(
        self, coord: EnphaseCoordinator, entry: EnphaseConfigEntry, sn: str
    ) -> None:
        super().__init__(
            coord,
            entry,
            sn,
            unique_suffix="schedule_edit_start_time",
            translation_key="evse_schedule_edit_start_time",
            key="start_time",
        )

    async def async_set_value(self, value: dt_time) -> None:
        if self._editor is not None:
            self._editor.set_edit_time(self._sn, "start_time", value)


class EvseScheduleEditEndTimeEntity(_EvseScheduleEditorTimeEntity):
    def __init__(
        self, coord: EnphaseCoordinator, entry: EnphaseConfigEntry, sn: str
    ) -> None:
        super().__init__(
            coord,
            entry,
            sn,
            unique_suffix="schedule_edit_end_time",
            translation_key="evse_schedule_edit_end_time",
            key="end_time",
        )

    async def async_set_value(self, value: dt_time) -> None:
        if self._editor is not None:
            self._editor.set_edit_time(self._sn, "end_time", value)
