from __future__ import annotations

from datetime import time as dt_time
import logging
import re

from homeassistant.components.time import TimeEntity
from homeassistant.core import HomeAssistant, callback
from homeassistant.helpers import entity_registry as er
from homeassistant.helpers.entity import DeviceInfo
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.update_coordinator import CoordinatorEntity

from .const import DOMAIN
from .coordinator import EnphaseCoordinator
from .log_redaction import redact_identifier
from .runtime_data import EnphaseConfigEntry, get_runtime_data

PARALLEL_UPDATES = 0
_LOGGER = logging.getLogger(__name__)
_AUTO_SUFFIX_RE = re.compile(r"^\d+$")


def _time_entity_id_migrations(coord: EnphaseCoordinator) -> dict[str, tuple[str, str]]:
    return {
        f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_start_time": (
            "time.charge_from_grid_start_time",
            "time.charge_from_grid_schedule_from_time",
        ),
        f"{DOMAIN}_site_{coord.site_id}_charge_from_grid_end_time": (
            "time.charge_from_grid_end_time",
            "time.charge_from_grid_schedule_to_time",
        ),
    }


def _migrated_time_entity_id(
    current_entity_id: str, legacy_entity_id: str, target_entity_id: str
) -> str | None:
    """Return canonical target entity_id, preserving numeric collision suffixes."""
    if current_entity_id == target_entity_id:
        return None

    # Keep already-migrated canonical auto-suffixed IDs unchanged.
    target_prefix = f"{target_entity_id}_"
    if current_entity_id.startswith(target_prefix):
        target_suffix = current_entity_id[len(target_prefix) :]
        if _AUTO_SUFFIX_RE.fullmatch(target_suffix):
            return None

    # Preserve legacy auto-suffixes generated by HA object-id collisions.
    legacy_prefix = f"{legacy_entity_id}_"
    if current_entity_id.startswith(legacy_prefix):
        suffix = current_entity_id[len(legacy_prefix) :]
        if _AUTO_SUFFIX_RE.fullmatch(suffix):
            return f"{target_entity_id}_{suffix}"

    # Strong migration mode: preserve any trailing numeric suffix and
    # otherwise force canonical target IDs (including former custom IDs).
    base, _, suffix = current_entity_id.rpartition("_")
    if base and _AUTO_SUFFIX_RE.fullmatch(suffix):
        return f"{target_entity_id}_{suffix}"
    return target_entity_id


def _site_has_battery(coord: EnphaseCoordinator) -> bool:
    has_encharge = getattr(coord, "battery_has_encharge", None)
    return has_encharge is not False


def _type_available(coord: EnphaseCoordinator, type_key: str) -> bool:
    has_type_for_entities = getattr(coord, "has_type_for_entities", None)
    if callable(has_type_for_entities):
        return bool(has_type_for_entities(type_key))
    has_type = getattr(coord, "has_type", None)
    return bool(has_type(type_key)) if callable(has_type) else True


def _cfg_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "charge_from_grid_schedule_available", False):
        return True
    if not getattr(coord, "charge_from_grid_control_available", False):
        return False
    if not getattr(coord, "charge_from_grid_schedule_supported", False):
        return False
    if getattr(coord, "_battery_cfg_schedule_id", None) is None:
        return False
    start_time = getattr(coord, "battery_charge_from_grid_start_time", None)
    end_time = getattr(coord, "battery_charge_from_grid_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_charge_begin_time", None)
    end = getattr(coord, "_battery_charge_end_time", None)
    return begin is not None and end is not None


def _dtg_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "discharge_to_grid_schedule_available", False):
        return True
    if not getattr(coord, "discharge_to_grid_schedule_supported", False):
        return False
    start_time = getattr(coord, "battery_discharge_to_grid_start_time", None)
    end_time = getattr(coord, "battery_discharge_to_grid_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_dtg_begin_time", None)
    end = getattr(coord, "_battery_dtg_end_time", None)
    if begin is None:
        begin = getattr(coord, "_battery_dtg_control_begin_time", None)
    if end is None:
        end = getattr(coord, "_battery_dtg_control_end_time", None)
    return begin is not None and end is not None


def _rbd_schedule_edit_available(coord: EnphaseCoordinator) -> bool:
    if getattr(coord, "restrict_battery_discharge_schedule_available", False):
        return True
    if not getattr(coord, "restrict_battery_discharge_schedule_supported", False):
        return False
    start_time = getattr(coord, "battery_restrict_battery_discharge_start_time", None)
    end_time = getattr(coord, "battery_restrict_battery_discharge_end_time", None)
    if start_time is not None and end_time is not None:
        return True
    begin = getattr(coord, "_battery_rbd_begin_time", None)
    end = getattr(coord, "_battery_rbd_end_time", None)
    if begin is None:
        begin = getattr(coord, "_battery_rbd_control_begin_time", None)
    if end is None:
        end = getattr(coord, "_battery_rbd_control_end_time", None)
    return begin is not None and end is not None


async def async_setup_entry(
    hass: HomeAssistant,
    entry: EnphaseConfigEntry,
    async_add_entities: AddEntitiesCallback,
) -> None:
    coord: EnphaseCoordinator = get_runtime_data(entry).coordinator
    site_entities_added = False

    ent_reg = er.async_get(hass)
    rename_by_unique = _time_entity_id_migrations(coord)
    for registry_entry in er.async_entries_for_config_entry(ent_reg, entry.entry_id):
        migration = rename_by_unique.get(registry_entry.unique_id)
        if migration is None:
            continue
        legacy_entity_id, target_entity_id = migration
        migrated_entity_id = _migrated_time_entity_id(
            registry_entry.entity_id, legacy_entity_id, target_entity_id
        )
        if migrated_entity_id is None:
            continue
        try:
            ent_reg.async_update_entity(
                registry_entry.entity_id,
                new_entity_id=migrated_entity_id,
            )
        except ValueError:
            _LOGGER.debug(
                "Could not rename schedule time entity during migration (%s -> %s)",
                redact_identifier(registry_entry.entity_id),
                redact_identifier(migrated_entity_id),
            )

    @callback
    def _async_sync_site_entities() -> None:
        nonlocal site_entities_added
        if site_entities_added:
            return
        if not _site_has_battery(coord) or not _type_available(coord, "encharge"):
            return
        async_add_entities(
            [
                ChargeFromGridStartTimeEntity(coord),
                ChargeFromGridEndTimeEntity(coord),
                DischargeToGridStartTimeEntity(coord),
                DischargeToGridEndTimeEntity(coord),
                RestrictBatteryDischargeStartTimeEntity(coord),
                RestrictBatteryDischargeEndTimeEntity(coord),
            ],
            update_before_add=False,
        )
        site_entities_added = True

    add_listener = getattr(coord, "async_add_topology_listener", None)
    if not callable(add_listener):
        add_listener = getattr(coord, "async_add_listener", None)
    if callable(add_listener):
        entry.async_on_unload(add_listener(_async_sync_site_entities))
    _async_sync_site_entities()


class _BaseChargeFromGridTimeEntity(CoordinatorEntity, TimeEntity):
    _attr_has_entity_name = True

    def __init__(self, coord: EnphaseCoordinator, suffix: str) -> None:
        super().__init__(coord)
        self._coord = coord
        self._attr_unique_id = f"{DOMAIN}_site_{coord.site_id}_{suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        if not super().available:
            return False
        return _type_available(
            self._coord, "encharge"
        ) and _cfg_schedule_edit_available(self._coord)

    @property
    def device_info(self) -> DeviceInfo:
        type_device_info = getattr(self._coord, "type_device_info", None)
        info = type_device_info("encharge") if callable(type_device_info) else None
        if info is not None:
            return info
        return DeviceInfo(
            identifiers={(DOMAIN, f"type:{self._coord.site_id}:encharge")},
            manufacturer="Enphase",
        )


class ChargeFromGridStartTimeEntity(_BaseChargeFromGridTimeEntity):
    _attr_translation_key = "charge_from_grid_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(coord, "charge_from_grid_start_time")

    @property
    def suggested_object_id(self) -> str | None:
        return "charge_from_grid_schedule_from_time"

    @property
    def native_value(self) -> dt_time | None:
        return self._coord.battery_charge_from_grid_start_time

    async def async_set_value(self, value: dt_time) -> None:
        if self._coord.charge_from_grid_schedule_available:
            await self._coord.async_set_charge_from_grid_schedule_time(start=value)
            return
        await self._coord.async_update_cfg_schedule(start=value)


class ChargeFromGridEndTimeEntity(_BaseChargeFromGridTimeEntity):
    _attr_translation_key = "charge_from_grid_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(coord, "charge_from_grid_end_time")

    @property
    def suggested_object_id(self) -> str | None:
        return "charge_from_grid_schedule_to_time"

    @property
    def native_value(self) -> dt_time | None:
        return self._coord.battery_charge_from_grid_end_time

    async def async_set_value(self, value: dt_time) -> None:
        if self._coord.charge_from_grid_schedule_available:
            await self._coord.async_set_charge_from_grid_schedule_time(end=value)
            return
        await self._coord.async_update_cfg_schedule(end=value)


class _BaseNamedBatteryScheduleTimeEntity(CoordinatorEntity, TimeEntity):
    _attr_has_entity_name = True

    def __init__(
        self,
        coord: EnphaseCoordinator,
        *,
        suffix: str,
        availability_check,
        value_attr: str,
        setter_name: str,
        suggested_object_id: str,
    ) -> None:
        super().__init__(coord)
        self._coord = coord
        self._availability_check = availability_check
        self._value_attr = value_attr
        self._setter_name = setter_name
        self._suggested_object_id = suggested_object_id
        self._attr_unique_id = f"{DOMAIN}_site_{coord.site_id}_{suffix}"

    @property
    def available(self) -> bool:  # type: ignore[override]
        if not super().available:
            return False
        return _type_available(self._coord, "encharge") and self._availability_check(
            self._coord
        )

    @property
    def suggested_object_id(self) -> str | None:
        return self._suggested_object_id

    @property
    def native_value(self) -> dt_time | None:
        return getattr(self._coord, self._value_attr)

    @property
    def device_info(self) -> DeviceInfo:
        type_device_info = getattr(self._coord, "type_device_info", None)
        info = type_device_info("encharge") if callable(type_device_info) else None
        if info is not None:
            return info
        return DeviceInfo(
            identifiers={(DOMAIN, f"type:{self._coord.site_id}:encharge")},
            manufacturer="Enphase",
        )

    async def async_set_value(self, value: dt_time) -> None:
        await getattr(self._coord, self._setter_name)(
            **{self._schedule_endpoint_key(): value}
        )

    def _schedule_endpoint_key(self) -> str:
        return "start"


class _BaseNamedBatteryScheduleStartTimeEntity(_BaseNamedBatteryScheduleTimeEntity):
    def _schedule_endpoint_key(self) -> str:
        return "start"


class _BaseNamedBatteryScheduleEndTimeEntity(_BaseNamedBatteryScheduleTimeEntity):
    def _schedule_endpoint_key(self) -> str:
        return "end"


class DischargeToGridStartTimeEntity(_BaseNamedBatteryScheduleStartTimeEntity):
    _attr_translation_key = "discharge_to_grid_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="discharge_to_grid_start_time",
            availability_check=_dtg_schedule_edit_available,
            value_attr="battery_discharge_to_grid_start_time",
            setter_name="async_set_discharge_to_grid_schedule_time",
            suggested_object_id="discharge_to_grid_schedule_from_time",
        )


class DischargeToGridEndTimeEntity(_BaseNamedBatteryScheduleEndTimeEntity):
    _attr_translation_key = "discharge_to_grid_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="discharge_to_grid_end_time",
            availability_check=_dtg_schedule_edit_available,
            value_attr="battery_discharge_to_grid_end_time",
            setter_name="async_set_discharge_to_grid_schedule_time",
            suggested_object_id="discharge_to_grid_schedule_to_time",
        )


class RestrictBatteryDischargeStartTimeEntity(_BaseNamedBatteryScheduleStartTimeEntity):
    _attr_translation_key = "restrict_battery_discharge_start_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="restrict_battery_discharge_start_time",
            availability_check=_rbd_schedule_edit_available,
            value_attr="battery_restrict_battery_discharge_start_time",
            setter_name="async_set_restrict_battery_discharge_schedule_time",
            suggested_object_id="restrict_battery_discharge_schedule_from_time",
        )


class RestrictBatteryDischargeEndTimeEntity(_BaseNamedBatteryScheduleEndTimeEntity):
    _attr_translation_key = "restrict_battery_discharge_end_time"

    def __init__(self, coord: EnphaseCoordinator) -> None:
        super().__init__(
            coord,
            suffix="restrict_battery_discharge_end_time",
            availability_check=_rbd_schedule_edit_available,
            value_attr="battery_restrict_battery_discharge_end_time",
            setter_name="async_set_restrict_battery_discharge_schedule_time",
            suggested_object_id="restrict_battery_discharge_schedule_to_time",
        )
