name: Validate with hassfest

on:
  pull_request:
    paths:
      - 'custom_components/**'
      - 'quality_scale.yaml'
      - '.github/workflows/hassfest.yml'
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'custom_components/**'
      - 'quality_scale.yaml'
      - '.github/workflows/hassfest.yml'
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v4"
        - uses: "home-assistant/actions/hassfest@master"
